### ISSUE TITLE
Is the TwoImageData layer missing in the repo?

### ISSUE THREAD

**Issue by CHUNYUWANG** [aharley/segaware#2]

**Comment by aharley** [comment]
Ah! You can swap TwoImageData with ImageSegData. See the "res" example to see how to use ImageSegData. I'll fix this in the repo soon. Thanks for bringing it up.
The issue came from developing the VGG-based stuff with DeepLabV1 code, and the ResNet-based stuff with DeepLabV2 code.

**Comment by brisker** [comment]
@aharley 
how did you visualize these embeddings since they are tensors in size like 64(or larger than 3) * H * W?

![image](https://user-images.githubusercontent.com/13804492/32215603-5f7fcb50-be5d-11e7-83d1-b7a6facaf0a5.png)
![image](https://user-images.githubusercontent.com/13804492/32215629-6f8de798-be5d-11e7-96b8-34894c84fa68.png)

**Comment by aharley** [comment]
PCA compression down to 3 dimensions.
